---
version: "3.9"
services:
  mainnetwork:
    ports:
      - 8081:8081
      - 19000:19000
  mobileapp:
    image: akvo/akvo-node-24-alpine:20250923.073213.57d80cd
    command: ["./start.sh"]
    volumes:
      - akvo-mis-mobile-docker-sync:/app/node_modules:nocopy
      - ./app:/app:delegated
      - ./.git:/app/.git:ro
    working_dir: /app
    environment:
      - APK_NAME=${APK_NAME}
      - APK_SHORT_NAME=${APK_SHORT_NAME}
      - BACKEND_IP_ADDRESS=${IP_ADDRESS}
      - EXPO_TOKEN
      - SENTRY_ENV=${SENTRY_MOBILE_ENV}
      - SENTRY_DSN=${SENTRY_MOBILE_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_MOBILE_AUTH_TOKEN}
    network_mode: service:mainnetwork
volumes:
  akvo-mis-mobile-docker-sync:
    external: true
